### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire() 

### ISSUE THREAD

**Issue by DerekBuntin** [MisterPhilip/maintenance-mode#27]
Package Version: 1.3.*
Laravel Version: 5.8

When running the artisan command:

`php artisan down/up`

the following error is displayed:

`Call to undefined method Illuminate\Events\Dispatcher::fire() `

According to [this issue](https://github.com/kristijanhusak/laravel-form-builder/issues/492#issuecomment-473573012) 

In versions prior to Laravel 5.7, this method class name was fire but with Laravel 5.8, it is now dispatch.

In StartMaintenanceCommand.php change line 53 from:

`Event::fire(new MaintenanceModeEnabled($payload['time'], $payload['message'], $payload['view'], $payload['retry'], $payload['allowed']));`

To

`Event::dispatch(new MaintenanceModeEnabled($payload['time'], $payload['message'], $payload['view'], $payload['retry'], $payload['allowed']));`

And in EndMaintenanceCommand.php line 47 from:

`Event::fire(new MaintenanceModeDisabled($data['time'], $data['message'], $data['view'], $data['retry']));`

To

`Event::dispatch(new MaintenanceModeDisabled($data['time'], $data['message'], $data['view'], $data['retry']));`

These changes resolve the problem in the command line.

**Comment by MisterPhilip** [comment]
Thanks for the heads up! I'm not sure how I missed that this was deprecated back in L5.4, but hey it's fixed now in 1.3.1.

**Comment by zahirzohair** [comment]
@DerekBuntin I got the same issue on Laravel 5.8 but I cannot find the above mentioned file to change all those lines of code.

**Comment by MisterPhilip** [comment]
@zahirzohair what package version are you running?

**Comment by zahirzohair** [comment]
@MisterPhilip which package you mean ?
if you mean "misterphilip/maintenance-mode": "1.3.*". i use this one but still doesnt work.

**Comment by MisterPhilip** [comment]
And you've run `composer update`? Does `composer show -D` show `misterphilip/maintenance-mode 
   1.3.1`?

The reason I ask is because this was fixed in 1.3.1, but not 1.3.0. Both files were updated:
https://github.com/MisterPhilip/maintenance-mode/blob/master/src/MisterPhilip/MaintenanceMode/Console/Commands/StartMaintenanceCommand.php#L53
https://github.com/MisterPhilip/maintenance-mode/blob/master/src/MisterPhilip/MaintenanceMode/Console/Commands/EndMaintenanceCommand.php#L47

**Comment by zahirzohair** [comment]
@MisterPhilip  yes of course i run composer update and the composer show -D shows misterphilip/maintenance-mode 1.3.1 too. but still i get the same error.

**Comment by arabhossain** [comment]
Have a look, hopefully it could save your day
https://github.com/kristijanhusak/laravel-form-builder/issues/492#issuecomment-516397389
